FROM ubuntu:18.04 as tvm_base

RUN apt-get update && apt-get install -yq \
    python3 \
    python3-dev \
    python3-setuptools \
    python3-pip \
    python3-venv \
    gcc \
    g++ \
    cmake \
    git \
    vim \
    curl \
    build-essential autoconf flex bison \
    libtinfo-dev zlib1g-dev libedit-dev libxml2-dev \
    llvm-9-dev \
    default-jre default-jdk \
    && apt-get clean

ENV venv=/opt/venv

RUN python3 -m venv $venv && \
    /bin/bash -c "source $venv/bin/activate && \
    pip install --upgrade pip && \
    pip install pytest pytest-xdist pytest-depends pytest-testmon pytest-forked && \
    pip install numpy scipy requests mxnet \"Pillow<7\" matplotlib"

RUN /bin/bash -c "git clone https://github.com/verilator/verilator.git && cd verilator && git checkout v4.034 && autoconf && ./configure  && make -j 8 && make test && make install"

RUN \
  mkdir /working/ && \
  cd /working/ && \
  /bin/bash -c "echo \"deb https://repo.scala-sbt.org/scalasbt/debian all main\" > /etc/apt/sources.list.d/sbt.list"  && \
  /bin/bash -c "echo \"deb https://repo.scala-sbt.org/scalasbt/debian /\" > /etc/apt/sources.list.d/sbt_old.list" && \
  /bin/bash -c "curl -sL \"https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823\" | apt-key add" && \
  apt-get update && \
  apt-get install sbt && \
  apt-get clean
